import AppKit
import XCTest
@testable import Codenotch

final class ClipboardHistoryTests: XCTestCase {
    private let start = Date(timeIntervalSince1970: 1_800_000_000)

    private func text(_ string: String, at seconds: TimeInterval = 0) -> ClipboardEntry {
        ClipboardEntry(items: [ClipboardItem(representations: [ClipboardType.plainText: Data(string.utf8)])],
                       copiedAt: start.addingTimeInterval(seconds))
    }

    private func blob(bytes: Int, at seconds: TimeInterval) -> ClipboardEntry {
        ClipboardEntry(items: [ClipboardItem(representations: [
            ClipboardType.png: Data(repeating: UInt8(seconds.truncatingRemainder(dividingBy: 256)), count: bytes),
        ])], copiedAt: start.addingTimeInterval(seconds))
    }

    // MARK: History

    func testNewestFirst() {
        var history = ClipboardHistory()
        history.record(text("one", at: 0))
        history.record(text("two", at: 1))
        XCTAssertEqual(history.entries.map(\.plainText), ["two", "one"])
    }

    func testRepeatCopyMovesUpAndKeepsItsID() {
        var history = ClipboardHistory()
        let first = text("same", at: 0)
        history.record(first)
        history.record(text("other", at: 1))
        history.record(text("same", at: 2))

        XCTAssertEqual(history.entries.map(\.plainText), ["same", "other"])
        XCTAssertEqual(history.entries[0].id, first.id)
        XCTAssertEqual(history.entries[0].copiedAt, start.addingTimeInterval(2))
    }

    func testSameBytesAsDifferentTypesAreDifferentEntries() {
        let bytes = Data("<b>x</b>".utf8)
        let plain = ClipboardEntry(items: [ClipboardItem(representations: [ClipboardType.plainText: bytes])], copiedAt: start)
        let html = ClipboardEntry(items: [ClipboardItem(representations: [ClipboardType.html: bytes])], copiedAt: start)
        XCTAssertNotEqual(plain.contentHash, html.contentHash)
    }

    func testLimitEvictsOldest() {
        var history = ClipboardHistory(limit: 3)
        for index in 0..<5 { history.record(text("\(index)", at: TimeInterval(index))) }
        XCTAssertEqual(history.entries.map(\.plainText), ["4", "3", "2"])
    }

    func testLoweringLimitTrims() {
        var history = ClipboardHistory()
        for index in 0..<5 { history.record(text("\(index)", at: TimeInterval(index))) }
        history.limit = 2
        XCTAssertEqual(history.entries.map(\.plainText), ["4", "3"])
    }

    func testByteCeilingEvictsOldestButKeepsNewest() {
        let big = ClipboardHistory.maxTotalBytes / 2 + 1
        var history = ClipboardHistory()
        history.record(blob(bytes: big, at: 1))
        history.record(blob(bytes: big, at: 2))
        XCTAssertEqual(history.entries.count, 1)
        XCTAssertEqual(history.entries[0].copiedAt, start.addingTimeInterval(2))
    }

    func testPromoteRemoveClear() {
        var history = ClipboardHistory()
        let old = text("old", at: 0)
        history.record(old)
        history.record(text("new", at: 1))

        history.promote(old.id, at: start.addingTimeInterval(5))
        XCTAssertEqual(history.entries.map(\.plainText), ["old", "new"])
        XCTAssertEqual(history.entries[0].copiedAt, start.addingTimeInterval(5))

        history.remove(old.id)
        XCTAssertEqual(history.entries.map(\.plainText), ["new"])

        history.clear()
        XCTAssertTrue(history.entries.isEmpty)
    }

    // MARK: Capture

    func testPrivateMarkersAreRefused() {
        XCTAssertTrue(ClipboardCapture.isPrivate([ClipboardType.plainText, "org.nspasteboard.ConcealedType"]))
        XCTAssertTrue(ClipboardCapture.isPrivate(["org.nspasteboard.TransientType"]))
        XCTAssertTrue(ClipboardCapture.isPrivate(["org.nspasteboard.AutoGeneratedType"]))
        XCTAssertFalse(ClipboardCapture.isPrivate([ClipboardType.plainText, ClipboardType.html]))
    }

    func testUnknownTypesAreDropped() throws {
        let items = try XCTUnwrap(ClipboardCapture.normalise([[
            ClipboardType.plainText: Data("hi".utf8),
            "com.example.private": Data(repeating: 1, count: 100),
        ]]))
        XCTAssertEqual(Set(items[0].representations.keys), [ClipboardType.plainText])
    }

    func testNothingKeptIsNoEntry() {
        XCTAssertNil(ClipboardCapture.normalise([["com.example.private": Data([1])]]))
        XCTAssertNil(ClipboardCapture.normalise([]))
    }

    func testOversizedCopyIsSkipped() {
        let huge = Data(count: ClipboardCapture.maxEntryBytes + 1)
        XCTAssertNil(ClipboardCapture.normalise([[ClipboardType.png: huge]]))
    }

    func testFileKeepsURLAndNameButNotIcon() throws {
        let items = try XCTUnwrap(ClipboardCapture.normalise([[
            ClipboardType.fileURL: Data("file:///tmp/a.txt".utf8),
            ClipboardType.plainText: Data("a.txt".utf8),
            ClipboardType.tiff: Data(repeating: 7, count: 1000),
        ]]))
        XCTAssertEqual(Set(items[0].representations.keys), [ClipboardType.fileURL, ClipboardType.plainText])
    }

    func testTIFFBecomesPNG() throws {
        let items = try XCTUnwrap(ClipboardCapture.normalise([[ClipboardType.tiff: Self.tiff()]]))
        XCTAssertEqual(Set(items[0].representations.keys), [ClipboardType.png])
        XCTAssertNotNil(NSBitmapImageRep(data: items[0].representations[ClipboardType.png]!))
    }

    func testTIFFBesideAPNGIsDropped() throws {
        let png = Data([0x89, 0x50, 0x4E, 0x47])
        let items = try XCTUnwrap(ClipboardCapture.normalise([[ClipboardType.tiff: Self.tiff(), ClipboardType.png: png]]))
        XCTAssertEqual(items[0].representations, [ClipboardType.png: png])
    }

    // MARK: Kind and preview

    func testKinds() {
        func entry(_ types: [String: Data]) -> ClipboardEntry {
            ClipboardEntry(items: [ClipboardItem(representations: types)], copiedAt: start)
        }
        let word = Data("x".utf8)
        XCTAssertEqual(entry([ClipboardType.plainText: word]).kind, .text)
        XCTAssertEqual(entry([ClipboardType.plainText: word, ClipboardType.html: word]).kind, .richText)
        XCTAssertEqual(entry([ClipboardType.png: word, ClipboardType.html: word]).kind, .image)
        XCTAssertEqual(entry([ClipboardType.fileURL: Data("file:///a".utf8), ClipboardType.plainText: word]).kind, .files)
    }

    func testRichTextPreviewFallsBackToRTF() throws {
        let rtf = try NSAttributedString(string: "Bold move").data(
            from: NSRange(location: 0, length: 9),
            documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf])
        let entry = ClipboardEntry(items: [ClipboardItem(representations: [ClipboardType.rtf: rtf])], copiedAt: start)
        XCTAssertEqual(entry.plainText, "Bold move")
    }

    func testFileURLsOnePerItem() {
        let entry = ClipboardEntry(items: [
            ClipboardItem(representations: [ClipboardType.fileURL: Data("file:///tmp/a.txt".utf8)]),
            ClipboardItem(representations: [ClipboardType.fileURL: Data("file:///tmp/b%20c.txt".utf8)]),
        ], copiedAt: start)
        XCTAssertEqual(entry.fileURLs.map(\.path), ["/tmp/a.txt", "/tmp/b c.txt"])
    }

    // MARK: Monitor

    private var pasteboard: NSPasteboard!

    override func setUp() {
        super.setUp()
        pasteboard = NSPasteboard.withUniqueName()
    }

    override func tearDown() {
        pasteboard.releaseGlobally()
        pasteboard = nil
        super.tearDown()
    }

    private func monitor(capturing into: @escaping (ClipboardEntry) -> Void) -> ClipboardMonitor {
        let monitor = ClipboardMonitor(pasteboard: pasteboard, now: { self.start },
                                       frontmostBundleID: { "com.example.editor" })
        monitor.onCapture = into
        return monitor
    }

    func testMonitorIgnoresWhatWasThereBeforeIt() {
        pasteboard.clearContents()
        pasteboard.setString("before", forType: .string)
        var captured: [ClipboardEntry] = []
        let monitor = monitor { captured.append($0) }
        monitor.poll()
        XCTAssertTrue(captured.isEmpty)
    }

    func testMonitorCapturesACopyOnce() throws {
        var captured: [ClipboardEntry] = []
        let monitor = monitor { captured.append($0) }

        pasteboard.clearContents()
        pasteboard.setString("hello", forType: .string)
        monitor.poll()
        monitor.poll()

        XCTAssertEqual(captured.count, 1)
        let entry = try XCTUnwrap(captured.first)
        XCTAssertEqual(entry.plainText, "hello")
        XCTAssertEqual(entry.sourceBundleID, "com.example.editor")
        XCTAssertEqual(entry.copiedAt, start)
    }

    func testMonitorSkipsConcealedCopies() {
        var captured: [ClipboardEntry] = []
        let monitor = monitor { captured.append($0) }

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString("hunter2", forType: .string)
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        pasteboard.writeObjects([item])
        monitor.poll()

        XCTAssertTrue(captured.isEmpty)
    }

    func testWritingBackRestoresEveryRepresentationAndIsNotRecaptured() {
        var captured: [ClipboardEntry] = []
        let monitor = monitor { captured.append($0) }
        let html = Data("<b>hi</b>".utf8)
        let entry = ClipboardEntry(items: [ClipboardItem(representations: [
            ClipboardType.plainText: Data("hi".utf8),
            ClipboardType.html: html,
        ])], copiedAt: start)

        monitor.write(entry)
        monitor.poll()

        XCTAssertTrue(captured.isEmpty)
        XCTAssertEqual(pasteboard.string(forType: .string), "hi")
        XCTAssertEqual(pasteboard.data(forType: .html), html)
    }

    func testMonitorKeepsMultipleItems() throws {
        var captured: [ClipboardEntry] = []
        let monitor = monitor { captured.append($0) }

        pasteboard.clearContents()
        pasteboard.writeObjects([URL(fileURLWithPath: "/tmp/a.txt") as NSURL,
                                 URL(fileURLWithPath: "/tmp/b.txt") as NSURL])
        monitor.poll()

        let entry = try XCTUnwrap(captured.first)
        XCTAssertEqual(entry.kind, .files)
        XCTAssertEqual(entry.fileURLs.map(\.path), ["/tmp/a.txt", "/tmp/b.txt"])
    }

    static func tiff() -> Data {
        let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: 4, pixelsHigh: 4,
                                   bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true,
                                   isPlanar: false, colorSpaceName: .deviceRGB,
                                   bytesPerRow: 0, bitsPerPixel: 0)!
        return rep.tiffRepresentation!
    }
}

final class ClipboardStoreTests: XCTestCase {
    private var directory: URL!
    private var store: ClipboardStore { ClipboardStore(directory: directory) }
    private let start = Date(timeIntervalSince1970: 1_800_000_000.25)

    override func setUpWithError() throws {
        directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("ClipboardStoreTests-\(UUID().uuidString)", isDirectory: true)
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: directory)
    }

    private func entry(_ string: String, at seconds: TimeInterval) -> ClipboardEntry {
        ClipboardEntry(items: [
            ClipboardItem(representations: [ClipboardType.plainText: Data(string.utf8),
                                             ClipboardType.html: Data("<p>\(string)</p>".utf8)]),
            ClipboardItem(representations: [ClipboardType.png: Data([1, 2, 3])]),
        ], copiedAt: start.addingTimeInterval(seconds), sourceBundleID: "com.example.\(string)")
    }

    func testMissingDirectoryLoadsEmpty() {
        XCTAssertEqual(store.load(), ClipboardHistory())
    }

    func testRoundTrip() throws {
        var history = ClipboardHistory(limit: 25)
        history.record(entry("one", at: 0))
        history.record(entry("two", at: 1))
        try store.save(history)

        XCTAssertEqual(store.load(), history)
    }

    func testDirectoryIsPrivate() throws {
        try store.save(ClipboardHistory())
        let mode = try FileManager.default.attributesOfItem(atPath: directory.path)[.posixPermissions] as? Int
        XCTAssertEqual(mode, 0o700)
    }

    func testEvictedEntriesLeaveNoContentBehind() throws {
        var history = ClipboardHistory()
        let gone = entry("gone", at: 0)
        history.record(gone)
        history.record(entry("kept", at: 1))
        try store.save(history)

        history.remove(gone.id)
        try store.save(history)

        let folders = try FileManager.default.contentsOfDirectory(
            atPath: directory.appendingPathComponent("items").path)
        XCTAssertEqual(folders, [history.entries[0].id.uuidString])
        XCTAssertEqual(store.load(), history)
    }

    func testEntryWithMissingContentIsDropped() throws {
        var history = ClipboardHistory()
        let broken = entry("broken", at: 0)
        history.record(broken)
        history.record(entry("fine", at: 1))
        try store.save(history)

        try FileManager.default.removeItem(at: directory.appendingPathComponent("items")
            .appendingPathComponent(broken.id.uuidString))

        XCTAssertEqual(store.load().entries.map(\.plainText), ["fine"])
    }

    func testCorruptIndexStartsOver() throws {
        try store.save(ClipboardHistory())
        try Data("not json".utf8).write(to: directory.appendingPathComponent("history.json"))
        XCTAssertEqual(store.load(), ClipboardHistory())
    }

    func testDestroyRemovesEverything() throws {
        var history = ClipboardHistory()
        history.record(entry("one", at: 0))
        try store.save(history)

        try store.destroy()
        XCTAssertFalse(FileManager.default.fileExists(atPath: directory.path))
        XCTAssertNoThrow(try store.destroy())
    }
}
